rm(list=ls())
install.packages("astsa")
install.packages("tseries")
install.packages("forecast")
library(astsa)
library(tseries)
library(forecast)
data1=prodn
n=length(data1)
n1=ceiling(n*0.7)
data=data1[1:n1]
test=data1[(n1+1):n]
plot(data,type='l',main=" Time series plot of the Monthly Production Index from January 1948 to September 1969",xlab="Timepoints",ylab="Production Index")
acf(data,lag.max=100)
pacf(data,lag.max=100)
adf.test(data)
d1=diff(data)
plot(d1,type='l',main="Time series plot of detrended series",xlab="Timepoints",ylab="Detrended time series values")
acf(d1,lag.max=100,main="ACF Plot of first order differenced series")
ds=diff(d1,lag=12)
plot(ds,type='l',main="Time series plot of detrended, deseasonalized series",xlab="Timepoints",ylab="Detrended, deseasonalized values")
acf(ds,lag.max=12)
pacf(ds,lag.max=12)
acf(ds,lag.max=84,main="ACF Plot of detrended, deseasonalized series")
pacf(ds,lag.max=60,main="PACF Plot of detrended, deseasonalized series")
#
m1=arima(data,order=c(0,1,1),seasonal=list(order=c(0,1,1),period=12),method="ML")
m1$aic
f1=forecast(m1,h=length(test))
pf1=as.numeric(f1$mean)
rmse1=mean(sqrt((pf1-test)^2))
rmse1
#
m2=arima(data,order=c(1,1,1),seasonal=list(order=c(1,1,1),period=12),method="ML")
m2$aic
f2=forecast(m2,h=length(test))
pf2=as.numeric(f2$mean)
rmse2=mean(sqrt((pf2-test)^2))
rmse2
#
m3=arima(data,order=c(1,1,2),seasonal=list(order=c(1,1,1),period=12),method="ML")
m3$aic
f3=forecast(m3,h=length(test))
pf3=as.numeric(f3$mean)
rmse3=mean(sqrt((pf3-test)^2))
rmse3
#
m4=arima(data,order=c(1,1,2),seasonal=list(order=c(2,1,1),period=12),method="ML")
m4$aic
f4=forecast(m4,h=length(test))
pf4=as.numeric(f4$mean)
rmse4=mean(sqrt((pf4-test)^2))
rmse4
#
m5=arima(data,order=c(1,1,2),seasonal=list(order=c(0,1,1),period=12),method="ML")
m5$aic
f5=forecast(m5,h=length(test))
pf5=as.numeric(f5$mean)
rmse5=mean(sqrt((pf5-test)^2))
rmse5
#
m6=arima(data,order=c(0,1,2),seasonal=list(order=c(0,1,1),period=12),method="ML")
m6$aic
f6=forecast(m6,h=length(test))
pf6=as.numeric(f6$mean)
rmse6=mean(sqrt((pf6-test)^2))
rmse6
#
m7=arima(data,order=c(1,1,2),seasonal=list(order=c(0,1,1),period=12),method="ML")
m7$aic
f7=forecast(m7,h=length(test))
pf7=as.numeric(f7$mean)
rmse7=mean(sqrt((pf7-test)^2))
rmse7
#
m8=arima(data,order=c(0,1,2),seasonal=list(order=c(3,1,1),period=12),method="ML")
m8$aic
f8=forecast(m8,h=length(test))
pf8=as.numeric(f8$mean)
rmse8=mean(sqrt((pf8-test)^2))
rmse8
#
m9=arima(data,order=c(0,1,2),seasonal=list(order=c(1,1,1),period=12),method="ML")
m9$aic
f9=forecast(m9,h=length(test))
pf9=as.numeric(f9$mean)
rmse9=mean(sqrt((pf9-test)^2))
rmse9
#
m10=arima(data,order=c(0,1,1),seasonal=list(order=c(3,1,1),period=12),method="ML")
m10$aic
f10=forecast(m10,h=length(test))
pf10=as.numeric(f10$mean)
rmse10=mean(sqrt((pf10-test)^2))
rmse10
#model_selected
m11=arima(data,order=c(2,1,2),seasonal=list(order=c(2,1,1),period=12),method="ML")
m11$aic
f11=forecast(m11,h=length(test))
pf11=as.numeric(f11$mean)
rmse11=mean(sqrt((pf11-test)^2))
rmse11
summary(m11)
plot(m11$residuals,main="Plot of residual series of ARIMA(2,1,2,2,1,1,12)",ylab="residuals")
acf(m11$residuals,lag.max=100,main="ACF plot of the residual series of the fitted model")
#
m12=arima(data,order=c(2,1,1),seasonal=list(order=c(2,1,1),period=12),method="ML")
m12$aic
f12=forecast(m12,h=length(test))
pf12=as.numeric(f12$mean)
rmse12=mean(sqrt((pf12-test)^2))
rmse12
#
m13=arima(data,order=c(2,1,2),seasonal=list(order=c(3,1,1),period=12),method="ML")
m13$aic
f13=forecast(m13,h=length(test))
pf13=as.numeric(f13$mean)
rmse13=mean(sqrt((pf13-test)^2))
rmse13
#
m14=arima(data,order=c(2,1,1),seasonal=list(order=c(1,1,1),period=12),method="ML")
m14$aic
f14=forecast(m14,h=length(test))
pf14=as.numeric(f14$mean)
rmse14=mean(sqrt((pf14-test)^2))
rmse14
#
m15=arima(data,order=c(2,1,1),seasonal=list(order=c(0,1,1),period=12),method="ML")
m15$aic
f15=forecast(m15,h=length(test))
pf15=as.numeric(f15$mean)
rmse15=mean(sqrt((pf15-test)^2))
rmse15
#
m16=arima(data,order=c(2,1,2),seasonal=list(order=c(1,1,1),period=12),method="ML")
m16$aic
f16=forecast(m16,h=length(test))
pf16=as.numeric(f16$mean)
rmse16=mean(sqrt((pf16-test)^2))
rmse16
#
m17=arima(data,order=c(2,1,2),seasonal=list(order=c(0,1,1),period=12),method="ML")
m17$aic
f17=forecast(m17,h=length(test))
pf17=as.numeric(f17$mean)
rmse17=mean(sqrt((pf17-test)^2))
rmse17
#
m18=arima(data,order=c(0,1,0),seasonal=list(order=c(1,1,1),period=12),method="ML")
m18$aic
#
m19=arima(data,order=c(1,1,0),seasonal=list(order=c(1,1,1),period=12),method="ML")
m19$aic
Box.test(m11$residuals,lag=25,type="Ljung-Box",fitdf=4)
adf.test(m11$residuals)
residual=m11$resid
plot(residual,main="Plot of residual series of ARIMA(2,1,2,2,1,1,12)",ylab="Residuals")

##forecast
f=forecast(m11,h=length(test))
plot(f)
f
pf=as.numeric(f$mean)
pf
plot(pf,type='l',ylim=c(80,180),main="Plot of the testing data and forecasted values",ylab="Series values",xlab="Timepoints",lty="dashed")
lines(test,type='l',col="black",lty="solid")
legend("topleft",legend=c("test series","forecasted values"),lty=c("solid","dashed"))

